Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [2]:
pip install numpy


In [3]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

# Check data types
print(f"Data type of list_: {type(list_)}")
print(f"Data type of array_list: {array_list.dtype}")


Data type of list_: <class 'list'>
Data type of array_list: <U1


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [4]:
# Data type of each element in list_
print("Data type of elements in list_:")
for elem in list_:
    print(type(elem))

# Data type of each element in array_list
print("Data type of elements in array_list:")
for elem in array_list:
    print(type(elem))


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

In [5]:
# Changing dtype of array_list to int
array_list = np.array(object = list_, dtype=int)

# Data type of each element in list_
print("Data type of elements in list_:")
for elem in list_:
    print(type(elem))

# Data type of each element in array_list
print("Data type of elements in array_list:")
for elem in array_list:
    print(type(elem))


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [6]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object = num_list)

# (i) Shape
print(f"Shape of num_array: {num_array.shape}")

# (ii) Size
print(f"Size of num_array: {num_array.size}")


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [7]:
# Create 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))

# Print the matrix
print(f"3x3 Zero Matrix:\n{zero_matrix}")


3x3 Zero Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [8]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the identity matrix
print(f"5x5 Identity Matrix:\n{identity_matrix}")


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
